//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.25 at 09:07:21 AM IST 
//


package com.airport.entities;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.airport.entities package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.airport.entities
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateAirportDetailsRequest }
     * 
     */
    public CreateAirportDetailsRequest createCreateAirportDetailsRequest() {
        return new CreateAirportDetailsRequest();
    }

    /**
     * Create an instance of {@link Airport }
     * 
     */
    public Airport createAirport() {
        return new Airport();
    }

    /**
     * Create an instance of {@link CreateAirportDetailsResponse }
     * 
     */
    public CreateAirportDetailsResponse createCreateAirportDetailsResponse() {
        return new CreateAirportDetailsResponse();
    }

    /**
     * Create an instance of {@link GellAllAirportDetailsResponse }
     * 
     */
    public GellAllAirportDetailsResponse createGellAllAirportDetailsResponse() {
        return new GellAllAirportDetailsResponse();
    }

    /**
     * Create an instance of {@link GetAirportDetailsRequest }
     * 
     */
    public GetAirportDetailsRequest createGetAirportDetailsRequest() {
        return new GetAirportDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAirportDetailsResponse }
     * 
     */
    public GetAirportDetailsResponse createGetAirportDetailsResponse() {
        return new GetAirportDetailsResponse();
    }

    /**
     * Create an instance of {@link UpdateAirportDetailsRequest }
     * 
     */
    public UpdateAirportDetailsRequest createUpdateAirportDetailsRequest() {
        return new UpdateAirportDetailsRequest();
    }

    /**
     * Create an instance of {@link UpdateAirportDetailsResponse }
     * 
     */
    public UpdateAirportDetailsResponse createUpdateAirportDetailsResponse() {
        return new UpdateAirportDetailsResponse();
    }

    /**
     * Create an instance of {@link DeleteAirportDetailsRequest }
     * 
     */
    public DeleteAirportDetailsRequest createDeleteAirportDetailsRequest() {
        return new DeleteAirportDetailsRequest();
    }

    /**
     * Create an instance of {@link DeleteAirportDetailsResponse }
     * 
     */
    public DeleteAirportDetailsResponse createDeleteAirportDetailsResponse() {
        return new DeleteAirportDetailsResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

}
